version: "3"
services:
  api:
    build: .
    container_name: icnea-server_2.0
    command: uvicorn run:app --host 0.0.0.0 --port 80 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    ports:
      - 80:80
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine